version: 2.0
jobs:
    build:
        docker:
            - image: mono:latest
        working_directory: ~/rsct/
        steps:
            - checkout
            - run:
                name: Install package dependencies
                command: apt-get update && apt-get install -y sox
            - run:
                name: Build
                command: xbuild /p:Configuration=Release RuneScapeCacheTools.sln
            - run:
                name: Test
                command: mono --debug packages/xunit.runner.console.*/tools/xunit.console.exe RuneScapeCacheToolsTests/bin/Release/RuneScapeCacheToolsTests.dll
